# Generated by Django 4.0.4 on 2022-05-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_biographical_info_profile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
