# Generated by Django 4.0.4 on 2022-05-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_slug_course_slug_parentcategory_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='parentcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
