# Generated by Django 4.0.4 on 2022-05-03 20:19

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_parent_category_remove_post_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('intro_content', ckeditor.fields.RichTextField(verbose_name='Intro Content')),
                ('detail_content', ckeditor.fields.RichTextField(verbose_name='Detail Content')),
                ('excerpt', models.TextField(blank=True, max_length=400)),
                ('hero_img', models.ImageField(upload_to='blog/images', verbose_name='Hero Image')),
                ('featured_img', models.ImageField(upload_to='blog/images', verbose_name='Featured Image')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
