# Generated by Django 4.0.4 on 2022-05-21 18:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_course_slug_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='gg', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='gg', editable=False, populate_from='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='gg', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='gg', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
