# Generated by Django 4.0.4 on 2022-05-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='subscribe_title',
        ),
        migrations.AddField(
            model_name='subscription',
            name='title',
            field=models.CharField(default='Subscribe Skolaku', max_length=100),
            preserve_default=False,
        ),
    ]
