# Generated by Django 4.0.4 on 2022-06-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_homepagecards_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'verbose_name': 'Bonus', 'verbose_name_plural': 'Bonuses'},
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name': 'General', 'verbose_name_plural': 'General'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.AlterField(
            model_name='general',
            name='name',
            field=models.CharField(default='General', editable=False, max_length=100),
        ),
    ]
