# Generated by Django 4.0.4 on 2022-06-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_bonus_options_alter_general_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('link_text', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='general',
            name='scripts_in_body',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='general',
            name='scripts_in_header',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
