# Generated by Django 4.0.4 on 2022-05-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_category_slug_remove_course_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
