# Generated by Django 4.0.4 on 2022-06-08 13:08

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_video_id_alter_course_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default='https://www.youtube.com/watch?v=dQw4w9WgXcQ', editable=False, max_length=140),
        ),
    ]
