# Generated by Django 4.0.4 on 2022-06-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_id',
        ),
    ]
